### ISSUE TITLE
Problems wit SQL

### ISSUE THREAD

**Issue by taunusweb** [salvaracer/ext-t3readspeaker#1]
Hi, thanks for this nice Extension, Version 1.2.2 works for me, while upgrading to Version 2.0.0 i get the following failure: `An exception occurred while executing 'SELECT `pid`, `uid`, `t3ver_oid`, `t3ver_wsid`, `t3ver_state`, `title`, `alias`, `nav_title`, `media`, `layout`, `hidden`, `starttime`, `endtime`, `fe_group`, `extendToSubpages`, `doktype`, `TSconfig`, `tsconfig_includes`, `is_siteroot`, `mount_pid`, `mount_pid_ol`, `fe_login_mode`, `backend_layout_next_level`, `tx_realurl_pathsegment`, `tx_realurl_exclude`, `tx_realurl_pathoverride`, `tx_t3readspeaker_lang`, `tx_t3readspeaker_voice` FROM `pages` WHERE (`uid` = ?) AND (`doktype` <> ?) AND (`pages`.`deleted` = 0)' with params [1, 255]: Unknown column 'tx_t3readspeaker_lang' in 'field list'`
TYPO3 Version 8.7.8.
Best Wishes
Uli

**Comment by davidlemaitre** [comment]
Confirm this bug, using TYPO3 8.7.15

**Comment by vergissberlin** [comment]
Hi @salvaracer,

currently the backend and frontend breaks totally down after the installation of your extension.
Please provide a new release as soon as possible!

Tanks, André

**Comment by vergissberlin** [comment]
@salvaracer Thank you, appreciate that!

**Comment by salvaracer** [comment]
In version 2.1.0, all settings moved to typoscript now, so the SQL error is the past! 💃
